# -*- coding: utf-8 -*-
"""api_server_stream.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1byU3zvM9H5K3xuEW1U1ALVUcP1GVH7WK

1️⃣ Imports + Flask Initialization
"""

# ==========================================
# Imports + Flask App Initialization
# ==========================================
from flask import Flask, jsonify, send_from_directory, Response, request
import time
import cv2
import traceback
import random  # Simulated Identity Recognition

from picamera2 import Picamera2
from emotion_engine import EmotionEngine

# Create Flask server
app = Flask(__name__)

"""2️⃣ Model Paths + Emotion Engine Initialization"""

# ==========================================
# Model + Detector Paths + Engine Init
# ==========================================
MODEL_PATH = "/home/kip/SmartMirror/emotion_model_best.h5"
CASCADE_PATH = "/usr/share/opencv4/haarcascades/haarcascade_frontalface_default.xml"

# Create EmotionEngine instance
engine = EmotionEngine(
    model_path=MODEL_PATH,
    cascade_path=CASCADE_PATH
)

"""3️⃣ Face ID Simulation"""

# ==========================================
# Fake Face-ID Recognition Setup
# ==========================================
MY_NAME = "Charaf"
RECOGNITION_SUCCESS_RATE = 0.90  # 90% success if face visible

"""4️⃣ Camera Initialization (with fail-safe mode)"""

# ==========================================
# Camera Init (with fallbacks)
# ==========================================
try:
    picam2 = Picamera2()
    config = picam2.create_preview_configuration(
        main={"size": (640, 480), "format": "BGR888"}
    )
    picam2.configure(config)
    picam2.start()
    time.sleep(1.0)
    camera_ok = True
    print("[INFO] Camera initialized successfully.")
except Exception as e:
    print("[FATAL] Camera failed to start:", e)
    traceback.print_exc()
    picam2 = None
    camera_ok = False

"""5️⃣ Shared State + Feedback Stats (No image storage)"""

# ==========================================
# Shared State + Feedback
# ==========================================
last_info = {
    "has_face": False,
    "face_box": None,
    "raw_emotion": None,
    "raw_confidence": 0.0,
    "stable_emotion": None,
    "is_charaf": False,  # Simulated ID result
    "message": "Willkommen! Bitte tritt vor den Spiegel. ✨",
    "longterm_emotion": None,
    "longterm_message": None,
    "history_count": 0,
}

# Anonymous feedback tracking
feedback_stats = {"total_correct": 0}

"""6️⃣ Flask API Routes"""

# ==========================================
# API Routes
# ==========================================
@app.route("/")
def index():
    return send_from_directory(".", "index.html")


@app.route("/status")
def status():
    info = last_info
    msg = info.get("message") if camera_ok else "Kamera konnte nicht gestartet werden (Device busy?)"

    return jsonify({
        "has_face": info["has_face"],
        "emotion": info["raw_emotion"],
        "confidence": info["raw_confidence"],
        "stable_emotion": info["stable_emotion"],
        "is_charaf": info["is_charaf"],
        "message": msg,
        "longterm_emotion": info["longterm_emotion"],
        "longterm_message": info["longterm_message"],
        "history_count": info["history_count"],
        "feedback_stats": feedback_stats,
    })


@app.route("/feedback", methods=["POST"])
def feedback():
    # User confirms correctness of recognition
    try:
        data = request.get_json(force=True)
    except:
        return jsonify({"ok": False, "error": "ungültiges JSON"}), 400

    emotion = data.get("emotion")
    correct = bool(data.get("correct"))

    if not emotion:
        return jsonify({"ok": False, "error": "Emotion fehlt"}), 400

    if correct:
        feedback_stats["total_correct"] += 1

    return jsonify({"ok": True, "feedback_stats": feedback_stats})

"""7️⃣ Stream Generation (Processing & Drawing)"""

# ==========================================
# Video Stream Generator
# ==========================================
def generate_stream():
    global last_info

    # If camera failed → send placeholder image
    if not camera_ok or picam2 is None:
        import numpy as np
        while True:
            img = np.zeros((240, 320, 3), dtype=np.uint8)
            cv2.putText(img, "Kamera-Fehler", (20, 60),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)
            _, jpeg = cv2.imencode(".jpg", img)
            yield b"--frame\r\nContent-Type: image/jpeg\r\n\r\n" + jpeg.tobytes() + b"\r\n"
            time.sleep(0.3)

    # Normal processing loop
    while True:
        # Capture frame
        frame = picam2.capture_array()
        frame = cv2.flip(frame, 1)

        # Run detection + emotion engine
        info = engine.process_frame(frame)

        # Simulated Face Recognition
        info["is_charaf"] = info.get("has_face") and (random.random() < RECOGNITION_SUCCESS_RATE)

        last_info = info

        # Draw face box + emotion text
        if info["face_box"]:
            x, y, w, h = info["face_box"]
            color = (0, 255, 0) if info["is_charaf"] else (0, 255, 255)
            cv2.rectangle(frame, (x, y), (x + w, y + h), color, 2)

            label = info["stable_emotion"] or info["raw_emotion"]
            if label:
                cv2.putText(frame, str(label).capitalize(),
                            (x, max(y - 10, 20)),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.7, color, 2)

        # Encode & send frame
        _, jpeg = cv2.imencode(".jpg", frame)
        yield b"--frame\r\nContent-Type: image/jpeg\r\n\r\n" + jpeg.tobytes() + b"\r\n"
        time.sleep(0.03)

"""8️⃣ Stream Endpoint + App Runner"""

# ==========================================
# Stream Route + Application Run
# ==========================================
@app.route("/stream")
def stream():
    return Response(generate_stream(),
                    mimetype="multipart/x-mixed-replace; boundary=frame")


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=False, threaded=True)