# -*- coding: utf-8 -*-
"""Emotion_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1id-kSxRyjqFdQtV126nUlT7RVAnWiqFQ

1️⃣ Imports
"""

# ==========================================
# Imports
# ==========================================
import time
import cv2
import numpy as np
from collections import Counter
from tensorflow.keras.models import load_model

"""2️⃣ EmotionEngine Klasse + init"""

# ==========================================
# EmotionEngine Class
# ==========================================
class EmotionEngine:
    """
    Kern-KI-Logik für den Smart Mirror.

    Features:
    - Haar-Cascade-Gesichtserkennung
    - Emotionserkennung mit Keras-Modell
    - Kurzzeit-Glättung (window_seconds, Mehrheitsentscheidung)
    - Reset nach no_face_timeout ohne Gesicht
    - Langzeitprotokollierung + Zusammenfassung
    """

    # ==============================
    # 1) INITIALISIERUNG / CONFIG
    # ==============================
    def __init__(
        self,
        model_path,
        cascade_path,
        emotion_labels=None,
        img_size=48,
        window_seconds=3.0,
        no_face_timeout=3.0,
        emotion_messages=None,
        default_message="Willkommen! Bitte tritt vor den Spiegel. ✨",
        min_confidence=0.15,
        history_interval=60.0,      # Sekunden zwischen Langzeit-Einträgen
        summary_required_logs=5,    # Anzahl Einträge vor Zusammenfassung
    ):
        # --- Pfade & Basis-Config ---
        self.model_path = model_path
        self.cascade_path = cascade_path
        self.img_size = img_size
        self.window_seconds = float(window_seconds)
        self.no_face_timeout = float(no_face_timeout)
        self.min_confidence = float(min_confidence)

        # --- Label-Set für das Modell ---
        if emotion_labels is None:
            self.emotion_labels = [
                "angry",
                "disgust",
                "fear",
                "happy",
                "neutral",
                "sad",
                "surprise",
            ]
        else:
            self.emotion_labels = emotion_labels

        # ==============================
        # 2) MESSAGING / TEXTE
        # ==============================
        # Kurzzeit-Nachrichten (Deutsch)
        if emotion_messages is None:
            self.emotion_messages = {
                "happy": "Du siehst heute fröhlich aus! 😊",
                "neutral": "Hab einen ruhigen, fokussierten Tag. 😌",
                "sad": "Alles in Ordnung? Atme einmal tief durch. 💙",
                "angry": "Gönn dir einen Moment Pause… Du schaffst das. 🔥",
                "fear": "Es ist okay, unsicher zu sein. Schritt für Schritt. 🌱",
                "disgust": "Etwas stört dich? Vielleicht hilft ein Umfeldwechsel. 🧠",
                "surprise": "Überrascht? Neuer Tag, neue Möglichkeiten! ✨",
            }
        else:
            self.emotion_messages = emotion_messages

        # Name, der vor jeder Emotionsnachricht steht
        self.person_name = "Charaf"   # <- Anzeigename hier ändern

        # Standardnachricht (wenn nichts erkannt)
        self.default_message = default_message

        # Nachricht, wenn KEIN Gesicht erkannt wird
        self.no_face_message = "Komm näher und schau in den Spiegel. ✨"

        # --- Langzeit-Stimmungs-Nachrichten ---
        self.longterm_messages = {
            "happy": "In letzter Zeit wirkst du insgesamt ziemlich fröhlich. Bleib so! ✨",
            "neutral": "Deine Stimmung war zuletzt meist ruhig und ausgeglichen. 😌",
            "sad": "Du hast in letzter Zeit öfter etwas bedrückt gewirkt. Sei lieb zu dir. 💙",
            "angry": "Du wirkst häufig angespannt. Vielleicht hilft eine kurze Pause oder ein Spaziergang. 🔥",
        }

        # ==============================
        # 3) BIAS-GEWICHTE
        # ==============================
        # 1.0 = neutral, >1 = verstärken, <1 = abschwächen
        self.bias_weights = {
            "angry": 1.18,
            "disgust": 1.0,
            "fear": 1.0,
            "happy": 0.95,
            "neutral": 0.90,
            "sad": 1.40,
            "surprise": 1.0,
        }

        # ==============================
        # 4) MODEL & CASCADE LADEN
        # ==============================
        self.model = load_model(self.model_path)

        self.face_cascade = cv2.CascadeClassifier(self.cascade_path)
        if self.face_cascade.empty():
            raise RuntimeError(f"Failed to load cascade from {self.cascade_path}")

        # ==============================
        # 5) KURZZEIT-STATE (GLÄTTUNG)
        # ==============================
        self.last_face_time = 0.0

        # Fenster für Mehrheitsentscheidung
        self.window_start_time = time.time()
        self.window_counts = {}  # emotion -> count

        # stabile Emotion (geglättet)
        self.stable_emotion = None
        self.stable_emotion_time = 0.0

        # letzte Roh-Emotion
        self.last_raw_emotion = None
        self.last_raw_confidence = 0.0

        # ==============================
        # 6) LANGZEIT-HISTORIE
        # ==============================
        self.history = []                  # Liste von stabilen Emotionen
        self.history_interval = float(history_interval)
        self.summary_required_logs = int(summary_required_logs)
        self.last_log_time = 0.0

        self.last_summary_emotion = None
        self.last_summary_message = None

"""3️⃣ preprocess_face"""

# ==============================
    # 7) HILFSFUNKTIONEN: PREPROCESS
    # ==============================
    def _preprocess_face(self, gray_frame, face_box):
        """
        Schneidet das Gesicht aus, skaliert auf img_size x img_size
        und normalisiert auf [0, 1].
        Erwartet ein Graustufenbild (gray_frame).
        """
        x, y, w, h = face_box

        # Safety-Clamp, damit Indizes gültig sind
        h_img, w_img = gray_frame.shape[:2]
        x = max(0, min(x, w_img - 1))
        y = max(0, min(y, h_img - 1))
        w = max(1, min(w, w_img - x))
        h = max(1, min(h, h_img - y))

        roi_gray = gray_frame[y : y + h, x : x + w]

        # Auf Modell-Inputgröße skalieren
        roi_resized = cv2.resize(roi_gray, (self.img_size, self.img_size))

        # Normalisieren
        roi_norm = roi_resized.astype("float32") / 255.0
        roi_input = np.expand_dims(roi_norm, axis=(0, -1))  # Shape: (1, H, W, 1)
        return roi_input

"""4️⃣ bias_correct_logits"""

# ==============================
    # 8) HILFSFUNKTIONEN: BIAS
    # ==============================
    def _bias_correct_logits(self, probs):
        """
        Wendet bias_weights auf die Roh-Output-Wahrscheinlichkeiten an
        und normalisiert anschließend wieder auf Summe 1.
        """
        probs = np.array(probs, dtype="float32")

        if probs.ndim != 1 or probs.shape[0] != len(self.emotion_labels):
            # Falls Shape unerwartet → lieber unverändert zurückgeben
            return probs

        adj = probs.copy()

        for label, weight in self.bias_weights.items():
            if label in self.emotion_labels:
                idx = self.emotion_labels.index(label)
                adj[idx] *= float(weight)

        s = adj.sum()
        if s > 0:
            adj /= s
        else:
            adj = probs

        return adj

"""5️⃣ update_longterm"""

# ==============================
    # 9) LANGZEIT-UPDATE
    # ==============================
    def _update_longterm(self, current_time):
        """
        Alle history_interval Sekunden:
        - wenn stabile Emotion vorhanden, wird genau EIN Log-Eintrag erzeugt
        - nach summary_required_logs Einträgen wird eine Zusammenfassung gebildet
        """
        if self.stable_emotion is None:
            # Keine stabile Emotion -> nichts loggen
            return

        # Zeitfenster prüfen
        if (self.last_log_time == 0.0) or (
            current_time - self.last_log_time >= self.history_interval
        ):
            # Einen neuen Eintrag für die aktuelle stabile Emotion speichern
            self.history.append(self.stable_emotion)
            self.last_log_time = current_time

            # Wenn genug Einträge vorhanden → Mehrheitsentscheidung
            if len(self.history) >= self.summary_required_logs:
                counts = Counter(self.history)
                winner, _ = counts.most_common(1)[0]
                self.last_summary_emotion = winner
                self.last_summary_message = self.longterm_messages.get(
                    winner, self.default_message
                )
                # Reset für neuen Langzeit-Zyklus
                self.history.clear()

"""6️⃣ process_frame"""

# ==============================
    # 🔁 10) HAUPT-API: process_frame
    # ==============================
    def process_frame(self, frame_bgr):
        """
        Hauptfunktion: verarbeitet ein BGR-Bild und gibt ein Info-Dict zurück:

        {
            "has_face": bool,
            "face_box": (x, y, w, h) oder None,
            "raw_emotion": str oder None,
            "raw_confidence": float,
            "stable_emotion": str oder None,
            "message": str,
            "longterm_emotion": str oder None,
            "longterm_message": str oder None,
            "history_count": int,
        }
        """
        current_time = time.time()

        # ----- Schritt 1: Gesichtserkennung -----
        gray = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2GRAY)
        faces = self.face_cascade.detectMultiScale(
            gray,
            scaleFactor=1.3,
            minNeighbors=5,
            minSize=(50, 50),
        )

        has_face = len(faces) > 0
        face_box = None
        raw_emotion = None
        raw_confidence = 0.0

        # ----- Schritt 2: Kein Gesicht → ggf. Reset -----
        if not has_face:
            if current_time - self.last_face_time > self.no_face_timeout:
                # Zustände zurücksetzen
                self.stable_emotion = None
                self.stable_emotion_time = 0.0
                self.window_counts = {}
                self.window_start_time = current_time
                self.last_raw_emotion = None
                self.last_raw_confidence = 0.0

        # ----- Schritt 3: Gesicht vorhanden -----
        else:
            # größtes Gesicht wählen
            areas = [(w * h, (x, y, w, h)) for (x, y, w, h) in faces]
            _, box = max(areas, key=lambda t: t[0])
            face_box = box

            self.last_face_time = current_time

            # Preprocessing
            face_input = self._preprocess_face(gray, face_box)

            # Modell-Prediction
            preds = self.model.predict(face_input, verbose=0)[0]
            preds_adj = self._bias_correct_logits(preds)

            best_idx = int(np.argmax(preds_adj))
            best_prob = float(preds_adj[best_idx])
            emo = self.emotion_labels[best_idx]

            # Sicherheits-Behandlung bei geringer Confidence
            if best_prob < self.min_confidence and "neutral" in self.emotion_labels:
                emo = "neutral"
                idx_neu = self.emotion_labels.index("neutral")
                best_prob = float(preds_adj[idx_neu])

            raw_emotion = emo
            raw_confidence = best_prob

            self.last_raw_emotion = raw_emotion
            self.last_raw_confidence = raw_confidence

            # Kurzzeitfenster zählen
            self.window_counts[raw_emotion] = self.window_counts.get(raw_emotion, 0) + 1

        # ----- Schritt 4: Kurzzeit-Glättung / stabile Emotion -----
        elapsed = current_time - self.window_start_time
        if elapsed >= self.window_seconds:
            if self.window_counts:
                # Emotion mit den meisten Votes im Fenster
                winner = max(self.window_counts.items(), key=lambda kv: kv[1])[0]
                if winner != self.stable_emotion:
                    self.stable_emotion = winner
                    self.stable_emotion_time = current_time
            else:
                self.stable_emotion = None
                self.stable_emotion_time = 0.0

            # Fenster zurücksetzen
            self.window_counts = {}
            self.window_start_time = current_time

        # ----- Schritt 5: Langzeit-Update -----
        self._update_longterm(current_time)

        # ----- Schritt 6: Nachricht generieren -----
        if not has_face:
            msg = self.no_face_message
        elif self.stable_emotion is not None:
            base_msg = self.emotion_messages.get(self.stable_emotion, self.default_message)
            msg = f"{self.person_name}, {base_msg}"
        elif self.last_raw_emotion is not None:
            base_msg = f"Du wirkst {self.last_raw_emotion}."
            msg = f"{self.person_name}, {base_msg}"
        else:
            msg = self.default_message

        # ----- Schritt 7: Ergebnisstruktur -----
        return {
            "has_face": has_face,
            "face_box": face_box,
            "raw_emotion": raw_emotion,
            "raw_confidence": raw_confidence,
            "stable_emotion": self.stable_emotion,
            "message": msg,
            "longterm_emotion": self.last_summary_emotion,
            "longterm_message": self.last_summary_message,
            "history_count": len(self.history),
        }