# -*- coding: utf-8 -*-
"""Gestik.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18bRJO57TZWg24qrOoYT95mJbmt8LCexc
"""

import os

for root, dirs, files in os.walk('/content', topdown=True):
    for name in files:
        if 'kaggle.json' in name:
            print("FOUND:", os.path.join(root, name))

# STEP 1: install kaggle
!pip install -q kaggle

import os, shutil

# make Kaggle config folder
os.makedirs("/root/.kaggle", exist_ok=True)

# move the uploaded kaggle.json into place if it exists
if os.path.exists("/content/kaggle.json"):
    shutil.move("/content/kaggle.json", "/root/.kaggle/kaggle.json")
else:
    raise FileNotFoundError("kaggle.json not found in /content. Upload it first in the file browser.")

# fix permissions (Kaggle CLI needs this)
os.chmod("/root/.kaggle/kaggle.json", 0o600)

# download LeapGestRecog dataset
!kaggle datasets download -d gti-upm/leapgestrecog -p /content

# unzip
!unzip -q /content/leapgestrecog.zip -d /content

# quick check
import os
print("Root folders in /content:")
print(os.listdir("/content"))

print("\nInside leapGestRecog:")
print(os.listdir("/content/leapGestRecog")[:15])

from pathlib import Path
import cv2
import numpy as np

ROOT = Path("/content/leapGestRecog")

# Our final classes
label_names = ["open", "peace", "fist", "none"]
label_to_idx = {name: i for i, name in enumerate(label_names)}

gesture_map = {
    "palm": "open",
    "palm_moved": "open",
    "fist": "fist",
    "fist_moved": "fist",
    "l": "peace",
    # all others → none
}

label_to_idx

IMG_SIZE = 64

X = []
y = []

subject_dirs = sorted([d for d in ROOT.iterdir() if d.is_dir()])

for subj in subject_dirs:
    gesture_dirs = sorted([g for g in subj.iterdir() if g.is_dir()])
    for gdir in gesture_dirs:
        gesture_full = gdir.name
        gesture_type = gesture_full.split("_", 1)[1]  # e.g. "palm"

        base_label = gesture_map.get(gesture_type, "none")
        label_idx = label_to_idx[base_label]

        for img_path in gdir.glob("*.png"):
            img = cv2.imread(str(img_path), cv2.IMREAD_GRAYSCALE)
            if img is None:
                continue

            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
            X.append(img)
            y.append(label_idx)

len(X), len(y)

X = np.array(X, dtype=np.float32)
y = np.array(y, dtype=np.int64)

X = X / 255.0
X = np.expand_dims(X, -1)

print("X shape:", X.shape)
print("y shape:", y.shape)
print("labels:", np.unique(y))

from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

y_cat = to_categorical(y, num_classes=len(label_names))

X_train, X_tmp, y_train, y_tmp = train_test_split(
    X, y_cat, test_size=0.3, random_state=42, stratify=y_cat
)

X_val, X_test, y_val, y_test = train_test_split(
    X_tmp, y_tmp, test_size=0.5, random_state=42, stratify=y_tmp
)

X_train.shape, X_val.shape, X_test.shape

import tensorflow as tf
from tensorflow.keras import layers, models

def build_gesture_model(input_shape=(IMG_SIZE, IMG_SIZE, 1), num_classes=4):
    model = models.Sequential([
        layers.Conv2D(32, (3,3), activation='relu', padding='same', input_shape=input_shape),
        layers.MaxPooling2D(2,2),

        layers.Conv2D(64, (3,3), activation='relu', padding='same'),
        layers.MaxPooling2D(2,2),

        layers.Conv2D(128, (3,3), activation='relu', padding='same'),
        layers.MaxPooling2D(2,2),

        layers.Flatten(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(num_classes, activation='softmax')
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(1e-3),
        loss="categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model

gesture_model = build_gesture_model()
gesture_model.summary()

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

datagen = ImageDataGenerator(
    rotation_range=10,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
)

callbacks = [
    EarlyStopping(monitor='val_accuracy', patience=3, restore_best_weights=True),
    ModelCheckpoint("gesture_model_best.h5", monitor='val_accuracy', save_best_only=True)
]

history = gesture_model.fit(
    datagen.flow(X_train, y_train, batch_size=64),
    epochs=15,
    validation_data=(X_val, y_val),
    callbacks=callbacks
)

loss, acc = gesture_model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", acc)

gesture_model.save("gesture_model.h5")

from google.colab import files
files.download("gesture_model.h5")